# This file was generated by GoReleaser. DO NOT EDIT.
cask "canvas-cli" do
  version "1.11.1"

  on_macos do
    on_intel do
      sha256 "b05808d7e56fcfbb0e263276a5d4facd226421d6bf52ea2a30ea507b6c477151"
      url "https://github.com/jjuanrivvera/canvas-cli/releases/download/v#{version}/canvas-cli_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ef1621aa1e10a467271d3044630a4583272b6238d4c7122a53048c9d77940223"
      url "https://github.com/jjuanrivvera/canvas-cli/releases/download/v#{version}/canvas-cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "721d5bc6da4a0860d83376634e8e1f1137255661e76159bd912d667daef7ad93"
      url "https://github.com/jjuanrivvera/canvas-cli/releases/download/v#{version}/canvas-cli_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2d41f1fc23a9e37c759af4c48cf0c4a5f88d24595a003fc91b6cf4f1c478b3cc"
      url "https://github.com/jjuanrivvera/canvas-cli/releases/download/v#{version}/canvas-cli_linux_arm64.tar.gz"
    end
  end

  name "canvas-cli"
  desc "A powerful command-line interface for Canvas LMS"
  homepage "https://github.com/jjuanrivvera/canvas-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "canvas"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/canvas"]
  end

  # No zap stanza required

end
