# This file was generated by GoReleaser. DO NOT EDIT.
cask "canvas-cli" do
  version "1.14.0"

  on_macos do
    on_arm do
      sha256 "e5207c1456ae85132f524a828823fe01edb261fa2c9a52296ffd80fe6bfc3b19"
      url "https://github.com/jjuanrivvera/canvas-cli/releases/download/v#{version}/canvas-cli_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "05abd3b2a01849bd7c04d695cfc34f4f61f2aa560b47bb9d8bfb8a0455504912"
      url "https://github.com/jjuanrivvera/canvas-cli/releases/download/v#{version}/canvas-cli_darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "071cda0497225fa727a47306b34d84fe1f7eb11b69dd67214000976ea8e48d3e"
      url "https://github.com/jjuanrivvera/canvas-cli/releases/download/v#{version}/canvas-cli_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bf984c4ef0b99978d7001c7e78170952c767bd305c5a227f890a58c045acbdc2"
      url "https://github.com/jjuanrivvera/canvas-cli/releases/download/v#{version}/canvas-cli_linux_x86_64.tar.gz"
    end
  end

  name "canvas-cli"
  desc "A powerful command-line interface for Canvas LMS"
  homepage "https://github.com/jjuanrivvera/canvas-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "canvas"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/canvas"]
  end

  # No zap stanza required
end
