# This file was generated by GoReleaser. DO NOT EDIT.
cask "canvas-cli" do
  version "1.15.0"

  on_macos do
    on_arm do
      sha256 "425358a0da037a885f53e7f78249bbb1c9ba01ccd8f954a909d62f9e3966eab4"
      url "https://github.com/jjuanrivvera/canvas-cli/releases/download/v#{version}/canvas-cli_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b0a8f959db5431d826f195100ecf9e85a9f2b6a4ad9da1ab592b74d363eeeca9"
      url "https://github.com/jjuanrivvera/canvas-cli/releases/download/v#{version}/canvas-cli_darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "79bb14fcf137a83c19f9e91f666775b2ab6fb0ba017cf99f0a083bc95f2a4faf"
      url "https://github.com/jjuanrivvera/canvas-cli/releases/download/v#{version}/canvas-cli_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2897d066fc48100ddb39d0f398421565b4b222d7cb165b7abd7849f38c35e888"
      url "https://github.com/jjuanrivvera/canvas-cli/releases/download/v#{version}/canvas-cli_linux_x86_64.tar.gz"
    end
  end

  name "canvas-cli"
  desc "A powerful command-line interface for Canvas LMS"
  homepage "https://github.com/jjuanrivvera/canvas-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "canvas"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/canvas"]
  end

  # No zap stanza required
end
