# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CanvasCli < Formula
  desc "A powerful command-line interface for Canvas LMS"
  homepage "https://github.com/jjuanrivvera/canvas-cli"
  version "1.10.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jjuanrivvera/canvas-cli/releases/download/v1.10.3/canvas-cli_darwin_x86_64.tar.gz"
      sha256 "4a4dae29717e033b138922bb37e52e4ff5abf2f4236b93e67081d7f5a922332e"

      define_method(:install) do
        bin.install "canvas"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jjuanrivvera/canvas-cli/releases/download/v1.10.3/canvas-cli_darwin_arm64.tar.gz"
      sha256 "7c8bf8d61b300ebb2dddfafde31d5987b611c70bac942a07d59f570e4bfbfb4b"

      define_method(:install) do
        bin.install "canvas"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jjuanrivvera/canvas-cli/releases/download/v1.10.3/canvas-cli_linux_x86_64.tar.gz"
      sha256 "103e0f16f58386913c6c77381dbcc8b10340f597900c23a4ff061d99409e2afa"
      define_method(:install) do
        bin.install "canvas"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jjuanrivvera/canvas-cli/releases/download/v1.10.3/canvas-cli_linux_arm64.tar.gz"
      sha256 "025d95e3c89d5ab831601e27c20444fa6db130c5ea1ea5f1053d78f92abaa58d"
      define_method(:install) do
        bin.install "canvas"
      end
    end
  end

  test do
    system "#{bin}/canvas", "version"
  end
end
