# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CanvasCli < Formula
  desc "A powerful command-line interface for Canvas LMS"
  homepage "https://github.com/jjuanrivvera/canvas-cli"
  version "1.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jjuanrivvera/canvas-cli/releases/download/v1.6.1/canvas-cli_darwin_x86_64.tar.gz"
      sha256 "a9fecce555e79ac49a1a8e400517ad798f78197ee2961a33ef78459639e9db6f"

      def install
        bin.install "canvas"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jjuanrivvera/canvas-cli/releases/download/v1.6.1/canvas-cli_darwin_arm64.tar.gz"
      sha256 "2f8ba4ebc87039e3bd2d51d345246eb62fd6d16a2462dfae289ddc29f8a16a76"

      def install
        bin.install "canvas"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jjuanrivvera/canvas-cli/releases/download/v1.6.1/canvas-cli_linux_x86_64.tar.gz"
      sha256 "4de43f736c0b5263ce3d8657f91b89326bc40f3bbf680f3816ad26689184bd96"
      def install
        bin.install "canvas"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jjuanrivvera/canvas-cli/releases/download/v1.6.1/canvas-cli_linux_arm64.tar.gz"
      sha256 "0f3f9a215782309dd3fc2a085d8addf0d151dfc9ca9b3cfe668bf50deb36cb30"
      def install
        bin.install "canvas"
      end
    end
  end

  test do
    system "#{bin}/canvas", "version"
  end
end
